"""refactor_base_with_common_mixin

Revision ID: 723d26151c2d
Revises: addcf1c1552e
Create Date: 2026-01-31 09:42:14.252696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '723d26151c2d'
down_revision: Union[str, Sequence[str], None] = 'addcf1c1552e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solvers_id'), table_name='solvers')
    op.create_index(op.f('ix_solvers_deleted_at'), 'solvers', ['deleted_at'], unique=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_index(op.f('ix_solvers_deleted_at'), table_name='solvers')
    op.create_index(op.f('ix_solvers_id'), 'solvers', ['id'], unique=False)
    # ### end Alembic commands ###
