"""add_proposal_table

Revision ID: b32bddb21b76
Revises: 928733f6fd44
Create Date: 2026-01-31 13:25:33.883903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b32bddb21b76'
down_revision: Union[str, Sequence[str], None] = '928733f6fd44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposals',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('solver_id', sa.Integer(), nullable=False),
    sa.Column('proposed_price', sa.Float(), nullable=False),
    sa.Column('cover_letter', sa.String(length=5000), nullable=True),
    sa.Column('proposal_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='proposal_status_type'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['solver_id'], ['solvers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_deleted_at'), 'proposals', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_proposals_project_id'), 'proposals', ['project_id'], unique=False)
    op.create_index(op.f('ix_proposals_solver_id'), 'proposals', ['solver_id'], unique=False)
    op.create_index(op.f('ix_proposals_uuid'), 'proposals', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposals_uuid'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_solver_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_project_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_deleted_at'), table_name='proposals')
    op.drop_table('proposals')
    # ### end Alembic commands ###
