"""add_project_compleation_table

Revision ID: e36771935a1e
Revises: 7d204b390771
Create Date: 2026-01-31 13:46:42.950691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e36771935a1e'
down_revision: Union[str, Sequence[str], None] = '7d204b390771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_completion_requests',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('completion_remark', sa.String(length=2000), nullable=False),
    sa.Column('solver_rating', sa.Float(), nullable=False),
    sa.Column('completion_status', sa.Enum('PENDING', 'APPROVED', 'REVISION_REQUESTED', 'CANCELLED', name='completion_status_type'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_completion_requests_deleted_at'), 'project_completion_requests', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_project_completion_requests_project_id'), 'project_completion_requests', ['project_id'], unique=True)
    op.create_index(op.f('ix_project_completion_requests_uuid'), 'project_completion_requests', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_completion_requests_uuid'), table_name='project_completion_requests')
    op.drop_index(op.f('ix_project_completion_requests_project_id'), table_name='project_completion_requests')
    op.drop_index(op.f('ix_project_completion_requests_deleted_at'), table_name='project_completion_requests')
    op.drop_table('project_completion_requests')
    # ### end Alembic commands ###
