"""add_buyer_table

Revision ID: 0fd12a6ebea1
Revises: 6084f23b2cc6
Create Date: 2026-01-31 10:16:07.480338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fd12a6ebea1'
down_revision: Union[str, Sequence[str], None] = '6084f23b2cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('business_url', sa.String(length=255), nullable=True),
    sa.Column('total_spent', sa.Float(), nullable=False),
    sa.Column('active_years', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('total_projects', sa.Integer(), nullable=False),
    sa.Column('completed_projects', sa.Integer(), nullable=False),
    sa.Column('is_hiring', sa.Enum('OPEN', 'CLOSED', 'PAUSED', name='hiring_status'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_buyers_deleted_at'), 'buyers', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_buyers_uuid'), 'buyers', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buyers_uuid'), table_name='buyers')
    op.drop_index(op.f('ix_buyers_deleted_at'), table_name='buyers')
    op.drop_table('buyers')
    # ### end Alembic commands ###
