"""add_staff_table

Revision ID: 162d4945e670
Revises: 0fd12a6ebea1
Create Date: 2026-01-31 11:07:38.517370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '162d4945e670'
down_revision: Union[str, Sequence[str], None] = '0fd12a6ebea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('responsibilities', sa.String(length=1000), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('department', sa.Enum('HR', 'IT', 'SALES', 'MARKETING', 'FINANCE', 'MODARATER', name='department_type'), nullable=False),
    sa.Column('is_available', sa.Enum('AVAILABLE', 'BUSY', 'OFFLINE', name='staff_availability_status'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_staff_deleted_at'), 'staff', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_staff_uuid'), 'staff', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_uuid'), table_name='staff')
    op.drop_index(op.f('ix_staff_deleted_at'), table_name='staff')
    op.drop_table('staff')
    # ### end Alembic commands ###
