"""add_task_submission_table

Revision ID: 7d204b390771
Revises: 163be93aa1c3
Create Date: 2026-01-31 13:36:37.282984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d204b390771'
down_revision: Union[str, Sequence[str], None] = '163be93aa1c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_submissions',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('buyer_feedback', sa.Enum('PENDING', 'APPROVED', 'REVISION_REQUESTED', 'REJECTED', name='buyer_feedback_type'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_submissions_deleted_at'), 'task_submissions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_task_submissions_task_id'), 'task_submissions', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_submissions_uuid'), 'task_submissions', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_submissions_uuid'), table_name='task_submissions')
    op.drop_index(op.f('ix_task_submissions_task_id'), table_name='task_submissions')
    op.drop_index(op.f('ix_task_submissions_deleted_at'), table_name='task_submissions')
    op.drop_table('task_submissions')
    # ### end Alembic commands ###
