"""solver_table

Revision ID: addcf1c1552e
Revises: 3e379da075bf
Create Date: 2026-01-30 19:27:28.329065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'addcf1c1552e'
down_revision: Union[str, Sequence[str], None] = '3e379da075bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solvers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('portfolio_url', sa.String(length=255), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('total_projects', sa.Integer(), nullable=False),
    sa.Column('completed_projects', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Enum('AVAILABLE', 'BUSY', 'OFFLINE', name='availability_status'), nullable=False),
    sa.Column('meta', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('skills', sa.ARRAY(sa.String(length=50)), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_solvers_id'), 'solvers', ['id'], unique=False)
    op.create_index(op.f('ix_solvers_uuid'), 'solvers', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solvers_uuid'), table_name='solvers')
    op.drop_index(op.f('ix_solvers_id'), table_name='solvers')
    op.drop_table('solvers')
    # ### end Alembic commands ###
